# version: 0.2
# env:
#   variables:
#     APP_ENV: 'prod'
# phases:
#   # use the install phase only for installing packages in the build environment
#   install:
#     runtime-versions:
#        nodejs: 18
#     commands:
#       - echo Install Angular CLI and all node_modules 
#       - cd $CODEBUILD_SRC_DIR/frontend/app-for-aws
#       - npm install && npm install -g @angular/cli
#   build:
#     commands:
#       - echo Build process started now
#       - cd $CODEBUILD_SRC_DIR/frontend/app-for-aws
#       - ng build --configuration=production
#   post_build:
#     commands:
#       - echo Build process finished, upload artifacts to S3 bucket
#       - cd dist/app-for-aws
#       - ls -la
# artifacts:
#   #  get files within the dist folder only
#   base-directory: 'frontend/app-for-aws/dist*'
#   discard-paths: yes
#   files:
#     - '**/*'  


version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - npm install -g aws-sdk
      - aws s3 cp s3://westworld-website-hosting-bucket1506 . --recursive
      - git clone https://github.com/waheed-15/java-application-serverless.git
  build:
    commands:
      - aws s3 sync java-application-serverless/ s3://westworld-website-hosting-bucket1506
